require('colorscheme.theme')
require('colorscheme.utils')

set_hl('Normal', theme.robdark.fg, theme.robdark.bg)
set_hl('Comment', theme.robdark.comment, 'none', 'italic')
set_hl({'Statement', 'Type', 'PreProc'}, theme.robdark.fg, 'none', 'bold')
set_hl('LineNr', theme.robdark.highlight, 'none')
set_hl('CursorLineNr', theme.robdark.accent, 'none', 'bold')
set_hl({'String', 'Character', 'Number'}, theme.robdark.string, 'none')
set_hl('SpecialChar', theme.robdark.fg, 'none', 'bold')
set_hl({'Visual', 'Pmenu'}, 'none', theme.robdark.visual)
set_hl('PmenuSel', 'none', theme.robdark.highlight, 'bold')
set_hl('Search', 'none', theme.robdark.highlight)
set_hl('IncSearch', 'none', theme.robdark.accent)
