require('colorscheme.theme')
require('colorscheme.utils')

set_hl('Normal', color.light[3], color.darker[4])
set_hl('Comment', color.light[7], 'none', 'italic')
set_hl({'Statement', 'Type', 'PreProc'}, color.light[3], 'none', 'bold')
set_hl('LineNr', color.darker[1], 'none')
set_hl('CursorLineNr', color.accent[1], 'none', 'bold')
set_hl({'String', 'Character', 'Number'}, color.light[6], 'none')
--set_hl('Special', color.light[1], 'none', 'bold')
set_hl('SpecialChar', color.light[5], 'none', 'bold')
set_hl({'Visual', 'Pmenu'}, 'none', color.darker[2])
set_hl('PmenuSel', 'none', color.darker[1], 'bold')
set_hl('Search', 'none', color.darker[1])
set_hl('IncSearch', 'none', color.accent[5])
