require('colorscheme.theme')
require('colorscheme.utils')

set_hl('Normal', color.light[1], color.dark[1])
set_hl('Comment', color.light[5], 'none', 'italic')
set_hl({'Statement', 'Type', 'PreProc'}, color.light[1], 'none', 'bold')
set_hl('LineNr', color.dark[3], 'none')
set_hl('CursorLineNr', color.accent[2], 'none', 'bold')
set_hl({'String', 'Character', 'Number'}, color.light[4], 'none')
--set_hl('Special', color.light[1], 'none', 'bold')
set_hl('SpecialChar', color.light[3], 'none', 'bold')
set_hl({'Visual', 'Pmenu'}, 'none', color.dark[2])
set_hl('PmenuSel', 'none', color.dark[3], 'bold')
set_hl('Search', 'none', color.dark[3])
set_hl('IncSearch', 'none', color.accent[5])
