require('colorscheme.theme')
require('colorscheme.utils')

set_hl('Normal', color.dark[1], color.light[1])
set_hl('Comment', color.dark[5], 'none', 'italic')
set_hl({'Statement', 'Type', 'PreProc'}, color.dark[1], 'none', 'bold')
set_hl('LineNr', color.light[3], 'none')
set_hl('CursorLineNr', color.accent[4], 'none', 'bold')
set_hl({'String', 'Character', 'Number'}, color.dark[4], 'none')
--set_hl('Special', color.dark[1], 'none', 'bold')
set_hl('SpecialChar', color.dark[2], 'none', 'bold')
set_hl({'Visual', 'Pmenu'}, 'none', color.light[2])
set_hl('PmenuSel', 'none', color.light[3], 'bold')
set_hl('Search', 'none', color.light[3])
set_hl('IncSearch', 'none', color.accent[5])
