require('colorscheme.theme')
require('colorscheme.utils')

set_hl('Normal', theme.roblight.fg, theme.roblight.bg)
set_hl('Comment', theme.roblight.comment, 'none', 'italic')
set_hl({'Statement', 'Type', 'PreProc'}, theme.roblight.fg, 'none', 'bold')
set_hl('LineNr', theme.roblight.highlight, 'none')
set_hl('CursorLineNr', theme.roblight.accent, 'none', 'bold')
set_hl({'String', 'Character', 'Number'}, theme.roblight.string, 'none')
set_hl('SpecialChar', theme.roblight.fg, 'none', 'bold')
set_hl({'Visual', 'Pmenu'}, 'none', theme.roblight.visual)
set_hl('PmenuSel', 'none', theme.roblight.highlight, 'bold')
set_hl('Search', 'none', theme.roblight.highlight)
set_hl('IncSearch', 'none', theme.roblight.accent)
