%hidden source_dir="#{d:current_file}"

run-shell -C "source-file $source_dir/options.conf"
run-shell -C "source-file $source_dir/keymaps.conf"

%if "#{==:$THEME,light}"
run-shell -C "source-file $source_dir/color-roblight.conf"
%else
run-shell -C "source-file $source_dir/color-robdark.conf"
%endif

run-shell -C "source-file $source_dir/theme.conf"
