# GENERAL --- {{{
set -g mouse on
unbind -T copy-mode-vi MouseDragEnd1Pane

# Enable RGB colour if running in xterm(1)
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# No more delay in vim
set -sg escape-time 0

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# 0 is too far from ` ;)
set -g base-index 1
# }}}
