# THEME --- {{{
# Status Bar
set -g status-bg $BG0
set -g status-fg $FG0

# Panes
set -g pane-border-style "fg=$FG2"
set -g pane-active-border-style "fg=$FG2"

# Tabs
setw -g window-status-style "fg=$FG4"
setw -g window-status-format "#I:#W"

setw -g window-status-current-style "fg=$GOLD"
setw -g window-status-current-format "#I:#W"

set -g status-left " "

set -g status-right-style "fg=$FG4"
set -g status-right "%b %d, %Y"
set -ga status-right " #[fg=$ACCENT]%H:%M "
# }}}
